<?php

namespace Customs\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyUserProxy extends \MyUser implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function Firstname()
    {
        $this->__load();
        return parent::Firstname();
    }

    public function Lastname()
    {
        $this->__load();
        return parent::Lastname();
    }

    public function isReviewer()
    {
        $this->__load();
        return parent::isReviewer();
    }

    public function ReviewInfo()
    {
        $this->__load();
        return parent::ReviewInfo();
    }

    public function Password()
    {
        $this->__load();
        return parent::Password();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ID', 'Username', 'Password', 'Email', 'PasswordChangeTimestamp', 'TemporaryResetPassword', 'TemporaryResetPasswordTimeout', 'LastLoginTimestamp', 'FailedLoginAttempts', 'LockTimeout', 'Activated', 'CreateTimestamp', 'Firstname', 'Lastname', 'isReviewer', 'ReviewInfo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}